/**
 * Logical resident-worker registry.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const STATE_VERSION = 1;
const STATE_ROOT = resolve(process.env.LOCALAPPDATA || process.env.HOME || '.', 'tradingview-mcp');
const STATE_FILE = join(STATE_ROOT, 'worker-state.json');

function defaultCapacity() { const configured = Number(process.env.TV_WORKER_MAX_CONNECTIONS || 50); return Number.isInteger(configured) && configured > 0 ? configured : 50; }
function defaultMaxChartsPerTab() { const configured = Number(process.env.TV_WORKER_MAX_CHARTS_PER_TAB || 8); return Number.isInteger(configured) && configured >= 1 && configured <= 8 ? configured : 8; }
const SUPPORTED_PANE_COUNTS = Object.freeze([8,6,4,3,2,1]);
export function planPaneCounts(entryCount,{maxChartsPerTab=defaultMaxChartsPerTab()}={}){const count=Number(entryCount),maxPerTab=Number(maxChartsPerTab);if(!Number.isInteger(count)||count<0)throw new Error('entry_count must be a non-negative integer');if(!Number.isInteger(maxPerTab)||maxPerTab<1||maxPerTab>8)throw new Error('max_charts_per_tab must be an integer from 1 to 8');if(count===0)return[];const supported=SUPPORTED_PANE_COUNTS.filter(v=>v<=maxPerTab),plan=[];let remaining=count;while(remaining>0){const paneCount=supported.find(v=>v<=remaining);if(!paneCount)throw new Error('No supported TradingView pane layout can represent the remaining entries');plan.push(paneCount);remaining-=paneCount;}return plan;}
export function planWorkerTopology(entries,{maxChartsPerTab=defaultMaxChartsPerTab()}={}){const list=entries||[],paneCounts=planPaneCounts(list.length,{maxChartsPerTab}),tabs=[];let offset=0;for(let index=0;index<paneCounts.length;index++){const pane_count=paneCounts[index],tabEntries=list.slice(offset,offset+pane_count);tabs.push({tab_index:index,pane_count,handles:tabEntries.map(e=>e.handle)});offset+=pane_count;}return{tab_count:tabs.length,max_charts_per_tab:Number(maxChartsPerTab),total_entries:list.length,tabs};}
function saveState(state){mkdirSync(STATE_ROOT,{recursive:true});const tmp=join(STATE_ROOT,`worker-state.${process.pid}.tmp`);writeFileSync(tmp,JSON.stringify(state,null,2),'utf8');renameSync(tmp,STATE_FILE);}
function loadState(){try{const state=JSON.parse(readFileSync(STATE_FILE,'utf8'));return state?.version===STATE_VERSION?state:null;}catch{return null;}}
function deps(overrides){return{loadState:overrides?.loadState||loadState,saveState:overrides?.saveState||saveState,now:overrides?.now||(()=>Date.now())};}
export function normalizeWorkerTimeframe(value){const raw=String(value??'').trim();if(!raw)throw new Error('timeframe is required');if(/^\d+$/.test(raw))return String(Number(raw));let m=raw.match(/^(\d+)s$/i);if(m)return String(Number(m[1]))+'S';m=raw.match(/^(\d+)(?:m|min)$/i);if(m)return String(Number(m[1]));m=raw.match(/^(\d+)h$/i);if(m)return String(Number(m[1])*60);m=raw.match(/^(\d+)d$/i);if(m)return String(Number(m[1]))+'D';m=raw.match(/^(\d+)w$/i);if(m)return String(Number(m[1]))+'W';m=raw.match(/^(\d+)(?:mo|month)$/i);if(m)return String(Number(m[1]))+'M';if(/^\d+M$/.test(raw))return raw;if(/^D$/i.test(raw))return'1D';if(/^W$/i.test(raw))return'1W';if(raw==='M')return'1M';return raw;}
function uniqueStrings(values,{sort=true}={}){const out=[],seen=new Set();for(const value of values||[]){const t=String(value??'').trim();if(!t)continue;const k=t.toUpperCase();if(seen.has(k))continue;seen.add(k);out.push(t);}return sort?out.sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'})):out;}
function stableValue(value){if(Array.isArray(value))return value.map(stableValue);if(value&&typeof value==='object'){const out={};for(const k of Object.keys(value).sort())out[k]=stableValue(value[k]);return out;}return value;}
function stableJson(v){return JSON.stringify(stableValue(v));}
export function normalizeStudySpecs(studies=[]){const byKey=new Map();for(const raw of studies||[]){let name,inputs;if(typeof raw==='string'){name=raw.trim();inputs=undefined;}else if(raw&&typeof raw==='object'&&!Array.isArray(raw)){name=String(raw.name??'').trim();if(raw.inputs!=null){if(!raw.inputs||typeof raw.inputs!=='object'||Array.isArray(raw.inputs))throw new Error('study inputs must be an object when provided');inputs=stableValue(raw.inputs);}}else throw new Error('Each study must be a name string or {name, inputs} object');if(!name)throw new Error('Each study requires a non-empty name');const key=name.toUpperCase()+'|'+stableJson(inputs??{});if(!byKey.has(key))byKey.set(key,inputs===undefined?{name}:{name,inputs});}return[...byKey.values()].sort((a,b)=>(a.name.toUpperCase()+'|'+stableJson(a.inputs??{})).localeCompare(b.name.toUpperCase()+'|'+stableJson(b.inputs??{})));}
export function buildWorkerKey({symbol,timeframe,studies=[]}){const s=String(symbol??'').trim();if(!s)throw new Error('symbol is required');return[s.toUpperCase(),normalizeWorkerTimeframe(timeframe).toUpperCase(),...normalizeStudySpecs(studies).map(x=>x.name.toUpperCase()+':'+stableJson(x.inputs??{}))].join('|');}
function generatedHandle(key){return'w_'+createHash('sha256').update(key).digest('hex').slice(0,12);}
function normalizeEntry(raw,previousByKey){const symbol=String(raw?.symbol??'').trim();if(!symbol)throw new Error('Each worker entry requires symbol');const timeframe=normalizeWorkerTimeframe(raw?.timeframe),studies=normalizeStudySpecs(raw?.studies),groups=uniqueStrings(raw?.groups),key=buildWorkerKey({symbol,timeframe,studies}),previous=previousByKey?.get(key)||null,requestedHandle=String(raw?.handle??'').trim(),handle=requestedHandle||previous?.handle||generatedHandle(key);return{handle,key,symbol,timeframe,studies,groups,assignment:previous?.assignment||null};}
export function normalizeWorkerUniverse(entries,{capacity=defaultCapacity(),reserveSlots=0,previousEntries=[]}={}){const cap=Number(capacity),reserve=Number(reserveSlots);if(!Number.isInteger(cap)||cap<1)throw new Error('capacity must be a positive integer');if(!Number.isInteger(reserve)||reserve<0||reserve>=cap)throw new Error('reserve_slots must be an integer from 0 up to capacity - 1');const previousByKey=new Map((previousEntries||[]).map(e=>[e.key,e])),byKey=new Map(),handleToKey=new Map();for(const raw of entries||[]){const entry=normalizeEntry(raw,previousByKey),existing=byKey.get(entry.key);if(existing){if(raw?.handle&&existing.handle!==entry.handle)throw new Error('Equivalent worker entry already uses handle "'+existing.handle+'"');existing.groups=uniqueStrings([...existing.groups,...entry.groups]);continue;}const prior=handleToKey.get(entry.handle);if(prior&&prior!==entry.key)throw new Error('Worker handle "'+entry.handle+'" is used by multiple distinct entries');handleToKey.set(entry.handle,entry.key);byKey.set(entry.key,entry);}const normalized=[...byKey.values()],usable=cap-reserve;if(normalized.length>usable)throw new Error('Worker universe exceeds usable capacity');return{capacity:cap,reserve_slots:reserve,usable_capacity:usable,entries:normalized};}
function buildGroupSummary(entries){const groups=new Map();for(const e of entries||[])for(const g of e.groups||[]){if(!groups.has(g))groups.set(g,[]);groups.get(g).push(e.handle);}return[...groups.entries()].map(([name,handles])=>({name,handles,count:handles.length})).sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base'}));}
function stateSummary(state){const entries=state?.entries||[],assigned=entries.filter(e=>e.assignment).length,maxCharts=state.max_charts_per_tab??defaultMaxChartsPerTab();return{success:true,configured:entries.length,assigned,unassigned:entries.length-assigned,capacity:state.capacity,reserve_slots:state.reserve_slots,usable_capacity:state.capacity-state.reserve_slots,free_slots:Math.max(0,state.capacity-state.reserve_slots-entries.length),max_charts_per_tab:maxCharts,topology_plan:planWorkerTopology(entries,{maxChartsPerTab:maxCharts}),groups:buildGroupSummary(entries),worker_tabs:state.worker_tabs||[],updated_at:state.updated_at||null,entries};}
export function setUniverse({entries=[],replace=true,capacity,reserve_slots,max_charts_per_tab,_deps}={}){const d=deps(_deps),previous=d.loadState(),effectiveCapacity=capacity??previous?.capacity??defaultCapacity(),effectiveReserve=reserve_slots??previous?.reserve_slots??0,effectiveMax=max_charts_per_tab??previous?.max_charts_per_tab??defaultMaxChartsPerTab();planPaneCounts(0,{maxChartsPerTab:effectiveMax});const combined=replace?entries:[...(previous?.entries||[]).map(e=>({handle:e.handle,symbol:e.symbol,timeframe:e.timeframe,studies:e.studies,groups:e.groups})),...entries];const normalized=normalizeWorkerUniverse(combined,{capacity:effectiveCapacity,reserveSlots:effectiveReserve,previousEntries:previous?.entries||[]});const state={version:STATE_VERSION,capacity:normalized.capacity,reserve_slots:normalized.reserve_slots,max_charts_per_tab:effectiveMax,worker_tabs:previous?.worker_tabs||[],updated_at:new Date(d.now()).toISOString(),entries:normalized.entries};d.saveState(state);return stateSummary(state);}
export function status({_deps}={}){const d=deps(_deps),state=d.loadState()||{version:STATE_VERSION,capacity:defaultCapacity(),reserve_slots:0,max_charts_per_tab:defaultMaxChartsPerTab(),worker_tabs:[],updated_at:null,entries:[]};return stateSummary(state);}
export function resolveWorkerSelection({handles=[],groups=[],_deps}={}){const state=status({_deps}),requestedHandles=uniqueStrings(handles,{sort:false}),requestedGroups=uniqueStrings(groups,{sort:false});if(!requestedHandles.length&&!requestedGroups.length)return{entries:state.entries,missing_handles:[],missing_groups:[]};const byHandle=new Map(state.entries.map(e=>[e.handle,e])),groupNames=new Set(state.groups.map(g=>g.name)),selected=new Map(),missing_handles=[],missing_groups=[];for(const h of requestedHandles){const e=byHandle.get(h);if(e)selected.set(e.key,e);else missing_handles.push(h);}for(const g of requestedGroups){if(!groupNames.has(g)){missing_groups.push(g);continue;}for(const e of state.entries)if((e.groups||[]).includes(g))selected.set(e.key,e);}return{entries:[...selected.values()],missing_handles,missing_groups};}
export function recordWorkerProvision({assignments={},worker_tabs,_deps}={}){const d=deps(_deps),state=d.loadState();if(!state)throw new Error('Worker universe is not configured');const entries=(state.entries||[]).map(e=>Object.prototype.hasOwnProperty.call(assignments,e.handle)?{...e,assignment:assignments[e.handle]}:e);const next={...state,worker_tabs:worker_tabs??state.worker_tabs??[],updated_at:new Date(d.now()).toISOString(),entries};d.saveState(next);return stateSummary(next);}
